// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type HomeDocumentDataSlicesSlice =
  | HeroSectionSlice
  | ArrowSectionSlice
  | ProjectsSectionSlice
  | AboutSectionSlice

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

/**
 * Item in *Project → Project Labels*
 */
export interface ProjectDocumentDataProjectLabelsItem {
  /**
   * label field in *Project → Project Labels*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Role
   * - **API ID Path**: project.project_labels[].label
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  label: prismic.SelectField<'Role' | 'Technology' | 'Date', 'filled'>

  /**
   * Label Text field in *Project → Project Labels*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_labels[].label_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_text: prismic.KeyTextField
}

/**
 * Item in *Project → Project Image*
 */
export interface ProjectDocumentDataProjectImageItem {
  /**
   * Images field in *Project → Project Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_image[].images
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  images: prismic.ImageField<never>
}

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Main Project Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.main_project_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_project_image: prismic.ImageField<never>

  /**
   * Project Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_title: prismic.KeyTextField

  /**
   * Project Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  project_description: prismic.RichTextField

  /**
   * Project Labels field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_labels[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project_labels: prismic.GroupField<
    Simplify<ProjectDocumentDataProjectLabelsItem>
  >

  /**
   * View Button Text field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.view_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  view_button_text: prismic.KeyTextField

  /**
   * View Button Link field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.view_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  view_button_link: prismic.LinkField

  /**
   * Project Image field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project_image[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project_image: prismic.GroupField<
    Simplify<ProjectDocumentDataProjectImageItem>
  >
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, 'project', Lang>

export type AllDocumentTypes = HomeDocument | ProjectDocument

/**
 * Primary content in *AboutSection → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Marquee Text field in *AboutSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.marquee_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  marquee_text: prismic.KeyTextField
}

/**
 * Primary content in *AboutSection → Items*
 */
export interface AboutSectionSliceDefaultItem {
  /**
   * Accordian Heading field in *AboutSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].accordian_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accordian_heading: prismic.KeyTextField

  /**
   * Accordian Content field in *AboutSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].accordian_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  accordian_content: prismic.RichTextField
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AboutSectionSliceDefaultPrimary>,
  Simplify<AboutSectionSliceDefaultItem>
>

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSlice = prismic.SharedSlice<
  'about_section',
  AboutSectionSliceVariation
>

/**
 * Primary content in *ArrowSection → Primary*
 */
export interface ArrowSectionSliceDefaultPrimary {
  /**
   * Arrow Image field in *ArrowSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: arrow_section.primary.arrow_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  arrow_image: prismic.ImageField<never>

  /**
   * Arrow Description field in *ArrowSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: arrow_section.primary.arrow_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  arrow_description: prismic.RichTextField

  /**
   * Contact Text field in *ArrowSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: arrow_section.primary.contact_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_text: prismic.KeyTextField

  /**
   * Contact Link field in *ArrowSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: arrow_section.primary.contact_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact_link: prismic.LinkField
}

/**
 * Primary content in *ArrowSection → Items*
 */
export interface ArrowSectionSliceDefaultItem {
  /**
   * Social Icon field in *ArrowSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: arrow_section.items[].social_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_icon: prismic.ImageField<never>

  /**
   * Social Link field in *ArrowSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: arrow_section.items[].social_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_link: prismic.LinkField

  /**
   * Social Platform field in *ArrowSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: arrow_section.items[].social_platform
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_platform: prismic.KeyTextField
}

/**
 * Default variation for ArrowSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArrowSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ArrowSectionSliceDefaultPrimary>,
  Simplify<ArrowSectionSliceDefaultItem>
>

/**
 * Slice variation for *ArrowSection*
 */
type ArrowSectionSliceVariation = ArrowSectionSliceDefault

/**
 * ArrowSection Shared Slice
 *
 * - **API ID**: `arrow_section`
 * - **Description**: ArrowSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArrowSectionSlice = prismic.SharedSlice<
  'arrow_section',
  ArrowSectionSliceVariation
>

/**
 * Primary content in *HeroSection → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Hero Title 1 field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.hero_title_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title_1: prismic.KeyTextField

  /**
   * Hero Title 2 field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.hero_title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title_2: prismic.KeyTextField

  /**
   * Hero Image field in *HeroSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>

  /**
   * Hero Para field in *HeroSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.primary.hero_para
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_para: prismic.KeyTextField
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  'hero_section',
  HeroSectionSliceVariation
>

/**
 * Primary content in *ProjectsSection → Items*
 */
export interface ProjectsSectionSliceDefaultItem {
  /**
   * Projects field in *ProjectsSection → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_section.items[].projects
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  projects: prismic.ContentRelationshipField<'project'>
}

/**
 * Default variation for ProjectsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<ProjectsSectionSliceDefaultItem>
>

/**
 * Slice variation for *ProjectsSection*
 */
type ProjectsSectionSliceVariation = ProjectsSectionSliceDefault

/**
 * ProjectsSection Shared Slice
 *
 * - **API ID**: `projects_section`
 * - **Description**: ProjectsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSectionSlice = prismic.SharedSlice<
  'projects_section',
  ProjectsSectionSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataProjectLabelsItem,
      ProjectDocumentDataProjectImageItem,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceDefaultItem,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      ArrowSectionSlice,
      ArrowSectionSliceDefaultPrimary,
      ArrowSectionSliceDefaultItem,
      ArrowSectionSliceVariation,
      ArrowSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ProjectsSectionSlice,
      ProjectsSectionSliceDefaultItem,
      ProjectsSectionSliceVariation,
      ProjectsSectionSliceDefault,
    }
  }
}
