// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  about_section: dynamic(() => import('./AboutSection')),
  arrow_section: dynamic(() => import('./ArrowSection')),
  hero_section: dynamic(() => import('./HeroSection')),
  projects_section: dynamic(() => import('./ProjectsSection')),
}
